from __future__ import annotations

import re
import shutil
from dataclasses import dataclass
from importlib import resources
from pathlib import Path
from typing import Any


@dataclass(frozen=True, slots=True)
class ProjectTemplate:
    """Description of a built-in ABMForge project template."""

    name: str
    description: str


class TemplateError(ValueError):
    """Raised when a requested project template is not available."""


class ProjectExistsError(FileExistsError):
    """Raised when a project path cannot be safely created."""


_TEMPLATE_DESCRIPTIONS = {
    "grid": "Minimal grid-based ABM study template for researcher workflows.",
    "epidemic": "Grid-based SIR epidemic ABM study template for researcher workflows.",
    "network": "Network-based diffusion ABM study template for researcher workflows.",
}

_TEXT_SUFFIXES = {
    ".cfg",
    ".csv",
    ".ini",
    ".json",
    ".md",
    ".py",
    ".toml",
    ".txt",
    ".yaml",
    ".yml",
}


def list_templates() -> list[ProjectTemplate]:
    """Return built-in project templates available to the CLI."""

    return [
        ProjectTemplate(name=name, description=description)
        for name, description in sorted(_TEMPLATE_DESCRIPTIONS.items())
    ]


def template_names() -> tuple[str, ...]:
    """Return built-in project template names."""

    return tuple(template.name for template in list_templates())


def create_project(
    path: str | Path,
    *,
    template: str = "grid",
    force: bool = False,
) -> Path:
    """Create a new ABMForge study project from a built-in template.

    Parameters
    ----------
    path:
        Target project directory.
    template:
        Built-in template name.
    force:
        If true, remove an existing non-empty project directory first.

    Returns
    -------
    Path
        Absolute path to the created project directory.
    """

    available_templates = template_names()

    if template not in available_templates:
        available = ", ".join(available_templates)
        raise TemplateError(
            f"Unknown project template {template!r}. Available templates: {available}"
        )

    target = Path(path).expanduser().resolve()

    if target.exists() and not target.is_dir():
        raise ProjectExistsError(f"Project path exists and is not a directory: {target}")

    if target.exists() and any(target.iterdir()):
        if not force:
            raise ProjectExistsError(
                "Project directory already exists and is not empty: "
                f"{target}. Use --force to overwrite it."
            )

        shutil.rmtree(target)

    target.mkdir(parents=True, exist_ok=True)

    template_root = resources.files("abmforge.templates").joinpath("builtin").joinpath(template)

    if not template_root.is_dir():
        raise TemplateError(f"Template files are missing for {template!r}")

    context = {
        "project_name": target.name,
        "project_slug": _slugify_project_name(target.name),
    }

    _copy_tree(template_root, target, context)

    outputs_dir = target / "outputs"
    outputs_dir.mkdir(exist_ok=True)
    (outputs_dir / ".gitkeep").write_text("", encoding="utf-8")

    model_init = target / "model" / "__init__.py"
    if model_init.parent.exists() and not model_init.exists():
        model_init.write_text(
            '"""Study model package generated by ABMForge."""\n',
            encoding="utf-8",
        )

    return target


def _copy_tree(source: Any, target: Path, context: dict[str, str]) -> None:
    for child in source.iterdir():
        if child.name == "__pycache__":
            continue

        destination = target / child.name

        if child.is_dir():
            destination.mkdir(parents=True, exist_ok=True)
            _copy_tree(child, destination, context)
            continue

        _copy_file(child, destination, context)


def _copy_file(source: Any, destination: Path, context: dict[str, str]) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)

    if _is_text_file(destination.name):
        text = source.read_text(encoding="utf-8")

        for key, value in context.items():
            text = text.replace(f"{{{{ {key} }}}}", value)
            text = text.replace(f"{{{{{key}}}}}", value)

        destination.write_text(text, encoding="utf-8")
        return

    destination.write_bytes(source.read_bytes())


def _is_text_file(filename: str) -> bool:
    return Path(filename).suffix.lower() in _TEXT_SUFFIXES


def _slugify_project_name(name: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9_.-]+", "-", name.strip().lower())
    slug = slug.strip("-._")
    return slug or "abmforge-study"
